version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(levelname)s - %(message)s"  # ✅ Adds timestamp

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG

  file:
    class: logging.FileHandler
    filename: logs/logninja.log  # ✅ Change if necessary
    level: INFO
    formatter: standard

root:
  handlers: ["console", "file"]  # ✅ Logs to console and file
  level: INFO
